export const data = [
  { name: "Carlos Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
  { name: "John Doe", age: 28, city: "New York" },
  { name: "Jane Smith", age: 34, city: "Los Angeles" },
  { name: "Michael Johnson", age: 45, city: "Chicago" },
];
